apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuma-data
  namespace: lab
spec:
  storageClassName: longhorn-fast-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
